############################################################
@local = https://localhost:6999
@deploy = https://

############################################################
# local test requests
### add nodeId for pubone
POST {{local}}/addNodeId
content-type: application/json

{
    "publicKey": "MCowBQYDK2VwAyEAxyJH+dZqAh5Fib0ZiLdfqn6FQnxZFEwdLSUlLUWM+fs=",
    "timestamp": "",
    "signature": "GcsHEGY9lLfebwO4Kw85j71NDaNCEJMg0RD57gcWjeFsJOGG3F2GVeT4TXlbZ1tFPCckMH3t64rwv5tc0vbjBQ=="
}

### add nodeId for pubtwo
POST {{local}}/addNodeId
content-type: application/json

{
    "publicKey": "MCowBQYDK2VwAyEAPR4EQTQm/r/iLYNYEux8ixfAXMwpqtG6Z4HWoj4W+0w=",
    "timestamp": "",
    "signature": "DGPQYnuEPbC6xQiTBqL+v8C2SDyGdCmvzBWDXUSxcWbKAN3Qose9oNAarj0xMoOIPMtfGZ00bM+Lvcs9MZzjAw=="
}

### from pubone
POST {{local}}/getSecretSpace
content-type: application/json

{
    "publicKey": "MCowBQYDK2VwAyEAxyJH+dZqAh5Fib0ZiLdfqn6FQnxZFEwdLSUlLUWM+fs=",
    "timestamp": "",
    "signature": ""
}

### from pubtwo
POST {{local}}/getSecretSpace
content-type: application/json

{
    "publicKey": "MCowBQYDK2VwAyEAPR4EQTQm/r/iLYNYEux8ixfAXMwpqtG6Z4HWoj4W+0w=",
    "timestamp": "",
    "signature": ""
}

# response
# {
#     secretSpace: "" //encrypted json string
# }

### 
POST {{local}}/setSecret
content-type: application/json

{
    "publicKey": "",
    "secretKey": "",
    "secret": "",
    "timestamp": "",
    "signature": ""
}

###
POST {{local}}/setSecret
content-type: application/json

{
    "publicKey": "",
    "secretKey": "",
    "secret": "",
    "timestamp": "",
    "signature": ""
}

# response
# {
#     ok: true
# }

###
POST {{local}}/getSecret
content-type: application/json

{
    "publicKey": "",
    "secretKey": "",
    "timestamp": "",
    "signature": ""
}

# response
# {
#     secret: "",
#     secretLeaked: false
# }

###
POST {{local}}/startSharingSecretTo
content-type: application/json

{
    "shareTo": "",
    "publicKey": "",
    "secretKey": "",
    "timestamp": "",
    "signature": ""
}

# response
# {
#     ok: true
# }

###
POST {{local}}/stopSharingSecretTo
content-type: application/json

{
    "shareTo": "",
    "publicKey": "",
    "secretKey": "",
    "timestamp": "",
    "signature": ""
}

# response
# {
#     ok: true
# }

###
POST {{local}}/startSharingSecretSpaceTo
content-type: application/json

{
    "shareTo": "",
    "publicKey": "",
    "timestamp": "",
    "signature": ""
}

# response
# {
#     ok: true
# }

###
POST {{local}}/stopSharingSecretSpaceTo
content-type: application/json

{
    "shareTo": "",
    "publicKey": "",
    "timestamp": "",
    "signature": ""
}

# response
# {
#     ok: true
# }


############################################################
### deployment requests
POST {{deploy}}/route
content-type: application/json

{
}